# Generated by Django 4.0.5 on 2022-10-31 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_gestor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestor',
            name='is_gestor',
        ),
    ]
