# Generated by Django 4.0.5 on 2022-11-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_gestor_id_alter_gestor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codigo',
            field=models.CharField(default='', max_length=32, verbose_name='Codigo'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_func',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome'),
        ),
    ]
