# Generated by Django 4.0.5 on 2022-11-02 11:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_codigo_user_is_func_user_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contato',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', help_text='Insira um número válido.', max_length=128, region='BR', unique=True),
        ),
    ]
