# Generated by Django 4.0.5 on 2022-10-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(max_length=32, verbose_name='Digite o nome da equipe')),
                ('cod_vendedor', models.CharField(max_length=32, verbose_name='Digite o codigo do vendedor')),
                ('nome', models.CharField(max_length=32, verbose_name='Digite seu nome')),
                ('email', models.EmailField(max_length=32, verbose_name='Digite seu email')),
                ('codigo', models.IntegerField()),
                ('frequencia', models.IntegerField()),
                ('data', models.DateField()),
            ],
        ),
    ]
