# Generated by Django 4.0.5 on 2022-10-21 16:56

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32, unique=True, verbose_name='Digite o nome da equipe')),
                ('codigoV', models.CharField(max_length=32, verbose_name='Digite o codigo do vendedor')),
                ('contato', phonenumber_field.modelfields.PhoneNumberField(help_text='Insira um número válido.', max_length=128, region='BR', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('frequencia', models.IntegerField()),
                ('data', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terça', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabádo', 'Sabado')], max_length=20)),
                ('mes', models.CharField(default='Escolha um mês', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('equipeNome', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='relatorio.equipe', verbose_name='Nome da Equipe')),
            ],
        ),
    ]
