# Generated by Django 4.0.5 on 2022-10-15 09:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='contato',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR', unique=True),
        ),
    ]
