# Generated by Django 4.0.5 on 2022-11-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0002_remove_equipe_codigov_remove_equipe_contato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='codigo_cliente',
            field=models.CharField(default='', max_length=32),
        ),
    ]
