# Generated by Django 4.0.5 on 2022-10-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0003_alter_equipe_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='nome',
            field=models.CharField(max_length=32, unique=True, verbose_name='Digite o nome da equipe'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='data',
            field=models.CharField(choices=[('segunda', 'Segunda-feira'), ('terça', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabádo', 'Sabado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='mes',
            field=models.CharField(default='Escolha um mês', max_length=10),
        ),
    ]
