# Generated by Django 4.0.5 on 2022-11-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0003_relatorio_codigo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='codigo_cliente',
            field=models.CharField(default='', max_length=32, verbose_name='Código do cliente'),
        ),
    ]
